source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '3.2.8'

gem 'twitter'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'

gem 'mysql2'

group :development,:test do
  gem 'taps'
  gem 'sqlite3'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
