B1;2cdevelopment:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: screenxtv_development
  pool: 5
  username: screenxtv
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: screenxtv_test
  pool: 5
  username: screenxtv
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  reconnect: false
  database: screenxtv_production
  pool: 5
  username: screenxtv
  host: 127.0.0.1
